
image: node:8.16.1-jessie

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
